name: DEV Auto deploy

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Check coding standard
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: ['18.x']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: Install dependencies
        run: npm i --legacy-peer-deps
      - run: npm run solhint
      - run: npm run prettier
